stages:
  - primary
  - extras

before_script:
  - git submodule update --init --recursive

cargo-test:
  image: gitlab.ae.cs.uni-frankfurt.de:5001/ae-ci/aeffm-rust-nightly
  stage: primary
  script:
    - cargo test

cargo-test-release:
  image: gitlab.ae.cs.uni-frankfurt.de:5001/ae-ci/aeffm-rust-nightly
  stage: extras
  script:
    - cargo test --release

cargo-clippy:
  image: gitlab.ae.cs.uni-frankfurt.de:5001/ae-ci/aeffm-rust-nightly
  stage: primary
  script:
    - cargo clippy --all-features -- -D clippy::all

cargo-format:
  image: gitlab.ae.cs.uni-frankfurt.de:5001/ae-ci/aeffm-rust-nightly
  stage: extras
  script:
    - cargo fmt --check

coverage:
  image: gitlab.ae.cs.uni-frankfurt.de:5001/ae-ci/aeffm-rust-nightly
  stage: extras
  coverage: '/^\d+.\d+% coverage/'
  script:
    - cargo tarpaulin -o xml -o html
  artifacts:
    reports:
      cobertura: cobertura.xml
    paths:
      - 'tarpaulin-report.html'
