[package]
name = "dfvs"
version = "0.1.0"
authors = ["Johannes Meintrup <johannes.meintrup@mni.thm.de>"]
edition = "2018"

[dependencies]
petgraph = "0.6.0"

[[bin]]
name = "dfvs-cli"
path = "src/main.rs"
test = false