[package]
name = "dfvs"
version = "0.1.0"
authors = ["Johannes Meintrup <johannes.meintrup@mni.thm.de>"]
edition = "2018"

[dependencies]
bitvec = "0.22.3"
num = "0.4.0"
bimap = "0.6.1"

[[bin]]
name = "dfvs-cli"
path = "src/main.rs"
test = false